### ISSUE TITLE
얘! 춘잣!위에도 컴파일이 된단다!

### ISSUE THREAD

**Issue by op06072** [hwan809/MungLang#1]
얘! 춘잣위에도 컴파일이 되버려서 주석으로 사용하려했는데 할 수가 없단다!
![스크린샷 2022-05-19 오후 6 21 22](https://user-images.githubusercontent.com/60420877/169283873-7c47b31b-cae0-4958-aaa6-c11cd7125663.png)

**Comment by hwan809** [comment]
죄송합니다.
지금부터는 제가 정리한 커밋을 보며 이야기..
https://github.com/hwan809/MungLang/commit/25e0273c2bbac08d0c5bbeb4b9bd844a9a1ce817
